# Generated by Django 3.1.5 on 2021-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='email',
            field=models.EmailField(default='tanka@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
