# Generated by Django 3.1.5 on 2021-01-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_modelname_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('re_enterpassword', models.TextField(max_length=100)),
            ],
        ),
    ]
